// inputs/Gender.tsx
"use client";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useInfoStore } from "@/state/infoStoreProvider";

export default function Gender() {
  const gender = useInfoStore((state) => state.gender);
  const setMale = useInfoStore((state) => state.setGenderMale);
  const setFemale = useInfoStore((state) => state.setGenderFemale);
  return (
    <RadioGroup value={gender}>
      <div className="flex items-center space-x-2">
        <RadioGroupItem onClick={setMale} value="male" id="male" />
        <Label htmlFor="option-one">Männlich</Label>
      </div>
      <div className="flex items-center space-x-2">
        <RadioGroupItem onClick={setFemale} value="female" id="female" />
        <Label htmlFor="option-two">Weiblich</Label>
      </div>
    </RadioGroup>
  );
}

// components/inputs/Gender/Gender.svelte
<script lang="ts">
	import { Label } from '$lib/components/ui/label';
	import * as RadioGroup from '$lib/components/ui/radio-group';
	import { getContext } from 'svelte';
	const inputData = getContext('inputData');
	let gender = 'undefined';
	$: inputData.set({ ...$inputData, gender });
</script>

<RadioGroup.Root bind:value={gender}>
	<div class="flex items-center space-x-2">
		<RadioGroup.Item value="male" id="male" />
		<Label for="option-one">Männlich</Label>
	</div>
	<div class="flex items-center space-x-2">
		<RadioGroup.Item value="female" id="female" />
		<Label for="option-two">Weiblich</Label>
	</div>
</RadioGroup.Root>
